name: recnn_env
channels:
  - defaults
  - conda-forge
dependencies:
  # Python version as specified
  - python=3.9

  # Essential packages
  - pip
  - git

  # Libraries explicitly installed
  - pip:
      - torch==1.9.0
      - torchvision
      - protobuf==3.19
      - wandb
      - -e git+https://github.com/lucabaroni/classical_exps.git@package-conversion#egg=classical_exps
      - -e git+https://github.com/lucabaroni/nnvision.git@model_builder#egg=nnvision
      - -e git+https://github.com/lucabaroni/neuralpredictors.git@recnn#egg=neuralpredictors

  # Uncommented dependencies to be included
  - pillow==9.2.0
  - numpy==1.21.1
  - scipy==1.7.0
  - tqdm==4.61.2

  # Optional: GPU compatibility libraries for PyTorch with CUDA 11.1
  - cudatoolkit=11.1

  # Uncomment these if additional packages are needed later
  # - pip:
  #     - moviepy
  #     - imageio
  #     - configparser==5.0.2
  #     - markdown==3.3.4
  #     - opencv-python==4.5.4.58
  #     - pytorch-lightning==1.5.2
  #     - pyyaml==5.4.1
  #     - requests==2.26.0
  #     - requests-oauthlib==1.3.0
  #     - termcolor==1.1.0
  #     - wget==3.2
  #     - statsmodels
  #     - param==1.5.1