method: bayes
metric:
  goal: maximize
  name: val/corr
name: sweep_brcnn_LSV1M
parameters:
  batch_size:
    values:
      - 4
      - 8
      - 16
      - 32
  depth_separable:
    values:
      - true
      - false
  gamma_hidden:
    values: [0.01, 0.005, 0.001, 0.0005, 0.0001]  # Include 0 and a placeholder for non-zero values
  gamma_input:
    values: [0.01, 0.005, 0.001, 0.0005, 0.0001]  # Include 0 and a placeholder for non-zero values
  hidden_channels:
    values:
      - 4
      - 8
      - 16
  hidden_kern:
    values:
      - 5
      - 7
      - 9
  init_sigma_range:
    values:
      - 0.1
  input_kern:
    values:
      - 3
      - 5
      - 7
  layers:
    values:
      - 4
      - 5
      - 6
      - 7
  lr_init:
    values: [0.01, 0.005, 0.001, 0.0005]
  rot_eq_batch_norm:
    values:
      - true
  upsampling:
    values: [1]
  fine_tune:
    values: ['core']
  do_not_sample:
    values: [True]
  # gamma_input_nonzero:
  #   distribution: q_log_uniform
  #   min: 0.0001  # small non-zero value to avoid log(0)
  #   max: 0.1
  #   q: 0.0001  # quantization step
  # gamma_hidden_nonzero:
  #   distribution: q_log_uniform
  #   min: 0.0001  # small non-zero value to avoid log(0)
  #   max: 0.05
  #   q: 0.0001  # quantization step