program: /project/monkey_training/hyper_params_search.py
name: sweep_brcnn
method: bayes
metric: 
  goal: maximize
  name: val/corr
parameters: 
  lr_init:
    values: [0.1, 0.01, 0.001, 0.0001]
  batch_size: 
    values: [128]
  upsampling: 
    values: [2]
  rot_eq_batch_norm: 
    values: [True]
  hidden_channels:
    values: [1]
  hidden_kern: 
    values: [3]
  input_kern: 
    values: [3]
  layers: 
    values: [2]
  gamma_hidden:
    distribution: q_log_uniform_values
    q: 0.0001
    max: 0.01
    min: 0.000001
  gamma_input: 
    distribution: q_log_uniform_values
    q: 0.0001
    max: 0.01
    min: 0.000001
  depth_separable: 
    values: [False]
  init_sigma_range: 
    values: [0.05, 0.1, 0.2]

  



  